[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_tic_tac_toe = "4LW9DrrBZDdVvo3Jm674zN2hbs1vaKnjQ96TD2dC36KC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/archuser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
